apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-managed-disk10
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: managed-premium
  resources:
    requests:
      storage: 10Gi