apiVersion: apps/v1
kind: Deployment
metadata:
  name: nick-demo-back
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nick-demo-back
  template:
    metadata:
      labels:
        app: nick-demo-back
    spec:
      containers:
      - name: nick-demo-back
        image: sparkdev/gowebdemo
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        ports:
        - containerPort: 8088
          name: gowebdemo
---
apiVersion: v1
kind: Service
metadata:
  name: nick-demo-back
spec:
  ports:
  - port: 8088
  selector:
    app: nick-demo-back
---
apiVersion: v1
kind: Service
metadata:
  name: nickdemo
  labels:
    app: nickdemo
spec:
  ports:
    - port: 80
  selector:
    app: nicknginx
  type: LoadBalancer
---
kind: Pod
apiVersion: v1
metadata:
  name: nicknginx
  labels:
    app: nicknginx
spec:
  containers:
  - name: nicknginx
    image: nginx:1.15.5
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 250m
        memory: 256Mi
    ports:
    - containerPort: 80
      name: nicknginx
    volumeMounts:
    - mountPath: "/mnt/azure"
      name: volume
    - mountPath: "/etc/nginx/conf.d"
      name: config
  volumes:
    - name: volume
      persistentVolumeClaim:
        claimName: azure-managed-disk10
    - name: config
      configMap:
        name: nginx-config
        items:
        - key: nginx.conf
          path: nginx.conf
  